language: java
jdk:
  - oraclejdk8

services:
  - postgresql

before_script:
  - psql -c 'create database mpws2016n1;' -U postgres
  - psql -f countries.sql -U postgres -d mpws2016n1

notifications:
  slack: hpi:80ADsgr1HVUFL8Q3IoDw3gSu