language: java
jdk:
  - oraclejdk8

before_install:
- mkdir -p $HOME/bin
- wget https://github.com/github/git-lfs/releases/download/v1.1.2/git-lfs-linux-amd64-1.1.2.tar.gz
- tar xvfz git-lfs-linux-amd64-1.1.2.tar.gz
- mv git-lfs-1.1.2/git-lfs $HOME/bin/git-lfs
- export PATH=$PATH:$HOME/bin/
- git lfs pull


notifications:
  slack: hpi:80ADsgr1HVUFL8Q3IoDw3gSu

cache:
  directories:
  - $HOME/.m2